name: Build Package
on:  # Trigger the workflow on push or pull request, but only for the master branch
  push:
    branches: [main, "release/*"]
  pull_request: {}

jobs:
  build-package:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install dependencies
      run: python -m pip install --user --upgrade setuptools wheel twine

    - name: Build packages
      run: |
        python setup.py sdist bdist_wheel
        ls -lh dist/

    - name: Check Package
      run: twine check dist/*

    - name: Install and Check Package Wheel
      run: |
        pip install ./dist/*.whl -f https://download.pytorch.org/whl/cpu/torch_stable.html
        python -c "import lightning_gpt; print(lightning_gpt.__version__); import mingpt.model; import nanogpt.model"

    - name: Install and Check Package Source Distribution
      run: |
        pip install ./dist/*.tar.gz --force-reinstall -f https://download.pytorch.org/whl/cpu/torch_stable.html
        python -c "import lightning_gpt; print(lightning_gpt.__version__); import mingpt.model; import nanogpt.model"

    - uses: actions/upload-artifact@v3
      with:
        name: pypi-packages-${{ github.sha }}
        path: dist
